services:
  mariadb:
    image: 'mariadb:11'
    container_name: 'mariadb'
    environment:
      - MARIADB_DATABASE=e-commercedb
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"