services:
  mysql:
    image: 'mysql:9.4.0'
    container_name: 'mysql'
    environment:
      - MYSQL_DATABASE=e-commercedb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"