spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/e-commercedb
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update